# Generated by Django 3.0.4 on 2020-09-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_route_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Route_number',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='Code',
            field=models.IntegerField(max_length=255),
        ),
    ]
