# Generated by Django 3.0.4 on 2020-09-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200929_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='Route_attached',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
