# Generated by Django 3.0.4 on 2020-09-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_village'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='formulae',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='Name',
            new_name='name',
        ),
    ]
