# Generated by Django 3.0.4 on 2020-09-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_code', models.IntegerField()),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('route_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('village_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('kilo', models.CharField(blank=True, max_length=255, null=True)),
                ('bm', models.CharField(blank=True, max_length=255, null=True)),
                ('cm', models.CharField(blank=True, max_length=255, null=True)),
                ('bm_cartage', models.CharField(blank=True, max_length=255, null=True)),
                ('cm_cartage', models.CharField(blank=True, max_length=255, null=True)),
                ('fat', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='centerimage')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='supervisor',
            old_name='Code',
            new_name='code',
        ),
    ]
