# Generated by Django 3.0.4 on 2020-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20200929_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='bm_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='bm_cartage_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='cm_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='cm_cartage_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='bank_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='kilo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
