# Generated by Django 3.0.4 on 2020-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200929_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='bank_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
