# Generated by Django 3.0.4 on 2020-09-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_auto_20200929_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
