# Generated by Django 3.0.4 on 2020-09-30 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_cowmilkrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowmilkrates',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Category'),
            preserve_default=False,
        ),
    ]
