# Generated by Django 3.0.4 on 2020-09-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_cowmilkrates_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowmilkrates',
            name='test',
        ),
    ]
