# Generated by Django 3.0.4 on 2020-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20200930_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='bm_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='bm_cartage_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='cm_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='cm_cartage_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
