# Generated by Django 3.0.4 on 2020-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20200930_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='bm_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='center',
            name='bm_cartage_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='center',
            name='cm_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='center',
            name='cm_cartage_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
