# Generated by Django 3.0.4 on 2020-09-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20200930_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmilkrates',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='commission_type',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='curd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='fat_from',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='fat_to',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='fixed_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='max_SNF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='max_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='min_SNF',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='min_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='min_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='penalty_in_RS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='premium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='sour_milk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='sour_milkrate',
            field=models.FloatField(default=0.0),
        ),
    ]
