# Generated by Django 3.0.4 on 2020-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_auto_20200930_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cowmilkrates',
            name='deduction_calculation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cowmilkrates',
            name='sour_milk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
