# Generated by Django 3.0.4 on 2020-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20201008_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowmilkcategory',
            name='milk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cowmilkcenter',
            name='milk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cowmilkroute',
            name='milk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
