# Generated by Django 3.1.2 on 2020-10-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20201009_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleno', models.IntegerField(default=0)),
                ('sampleno2', models.IntegerField(default=0)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('can', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('can', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DoK_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.IntegerField(default=0)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.FloatField(default=0.0)),
                ('cans', models.IntegerField(default=0)),
                ('samplecode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QC_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode', models.IntegerField(default=0)),
                ('fat', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='milk_type',
        ),
        migrations.RemoveField(
            model_name='cowmilkroute',
            name='milk_type',
        ),
        migrations.AddField(
            model_name='minmaxfat',
            name='milk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
