# Generated by Django 3.1.2 on 2020-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_auto_20201013_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleno', models.IntegerField(default=0)),
                ('sampleno2', models.IntegerField(default=0)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('can', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
            ],
        ),
    ]
