# Generated by Django 3.1.2 on 2020-10-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_daily_save'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily_Save',
        ),
    ]
