# Generated by Django 3.1.2 on 2020-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_dailyproc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproc',
            name='datefrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproc',
            name='dateto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproc',
            name='shift_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyproc',
            name='shift_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
