# Generated by Django 3.1.2 on 2020-10-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_auto_20201013_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dailyproc',
        ),
    ]
