# Generated by Django 3.1.2 on 2020-10-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_delete_dailyproc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minmaxfat',
            old_name='rate',
            new_name='tsrate',
        ),
    ]
