# Generated by Django 3.1.2 on 2020-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_auto_20201016_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='route_name',
        ),
        migrations.AddField(
            model_name='center',
            name='route_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='cm_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
