# Generated by Django 3.1.2 on 2020-10-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_auto_20201017_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='route_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
