# Generated by Django 3.1.2 on 2020-10-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_supervisor_route_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cowmilkroute',
            name='milk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
