# Generated by Django 3.1.2 on 2020-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_cowmilkroute_milk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='max_SNF',
        ),
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='max_fat',
        ),
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='min_SNF',
        ),
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='min_fat',
        ),
        migrations.RemoveField(
            model_name='cowmilkcenter',
            name='rate',
        ),
        migrations.AddField(
            model_name='cowmilkcenter',
            name='milk_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
