# Generated by Django 3.1.2 on 2020-10-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_auto_20201017_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_data',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='comm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='pel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='tsrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
