# Generated by Django 3.1.2 on 2020-10-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_auto_20201019_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='routecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
