# Generated by Django 3.1.2 on 2020-10-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_daily_data_routecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='dok_entry',
            name='routecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
