# Generated by Django 3.1.2 on 2020-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_branch_milktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Route_attached',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='code',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
