# Generated by Django 3.1.2 on 2020-10-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_auto_20201020_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='route_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dok_entry',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
