# Generated by Django 3.1.2 on 2020-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_auto_20201023_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='dok_entry',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dok_entry',
            name='bank_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dok_entry',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
