# Generated by Django 3.1.2 on 2020-10-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_auto_20201023_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='route_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dok_entry',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
