# Generated by Django 3.1.2 on 2020-10-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_auto_20201024_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='bank_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
