# Generated by Django 3.1.2 on 2020-10-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0061_auto_20201024_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='ltrrate',
            field=models.FloatField(default=0.0),
        ),
    ]
