# Generated by Django 3.1.2 on 2020-10-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0059_auto_20201026_1053'),
        ('school', '0062_daily_data_ltrrate'),
    ]

    operations = [
    ]
