# Generated by Django 3.1.2 on 2020-10-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0063_merge_20201027_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_data_excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='HDFC')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('BranchCode', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('Shift', models.CharField(max_length=255)),
                ('CenterCode', models.CharField(max_length=255)),
                ('MilkType', models.CharField(max_length=255)),
                ('Good_Sour', models.CharField(max_length=255)),
                ('SampleNo', models.FloatField(default=0.0)),
                ('Cans', models.FloatField(default=0.0)),
                ('Kgs', models.FloatField(default=0.0)),
                ('Fat', models.FloatField(default=0.0)),
                ('SNF', models.FloatField(default=0.0)),
                ('CLR', models.FloatField(default=0.0)),
                ('TSRATE', models.FloatField(default=0.0)),
                ('Rate', models.FloatField(default=0.0)),
                ('Comm', models.FloatField(default=0.0)),
                ('Amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='BRSHDFC',
        ),
        migrations.AddField(
            model_name='bank',
            name='bcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='contno',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pin',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
