# Generated by Django 3.1.2 on 2020-10-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0064_auto_20201029_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bcode',
            new_name='bankname',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='branchname',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulae',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milktype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
