# Generated by Django 3.1.2 on 2020-10-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0065_auto_20201030_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='branchname',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='bank_name',
            new_name='bankname',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='bank_no',
            new_name='bankno',
        ),
    ]
