# Generated by Django 3.1.2 on 2020-10-31 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0066_auto_20201031_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bankname',
            new_name='bank',
        ),
    ]
