# Generated by Django 3.1.2 on 2020-10-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0067_auto_20201031_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
