# Generated by Django 3.1.2 on 2020-11-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0068_center_ifsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_no', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('principal_amt', models.IntegerField(blank=True, null=True)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('flat_deminished', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_duration', models.IntegerField(blank=True, null=True)),
                ('interest_amt', models.FloatField(default=0.0)),
                ('noofinstallments', models.IntegerField(blank=True, null=True)),
                ('installment_amt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('issuedto', models.CharField(blank=True, max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('modeofreturn', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('closingdate', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
