# Generated by Django 3.1.2 on 2020-11-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0069_cloan_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloan',
            old_name='center',
            new_name='centername',
        ),
    ]
