# Generated by Django 3.1.2 on 2020-11-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0071_auto_20201102_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('issuedto', models.CharField(blank=True, max_length=255, null=True)),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('modeofreturn', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('issueddate', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='loan_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
