# Generated by Django 3.1.2 on 2020-11-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0072_auto_20201102_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='loan_no',
            new_name='Loanno',
        ),
    ]
