# Generated by Django 3.1.2 on 2020-11-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0073_auto_20201102_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='Loanno',
            new_name='loanno',
        ),
    ]
