# Generated by Django 3.1.2 on 2020-11-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0076_refund_loan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='depositno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
