# Generated by Django 3.1.2 on 2020-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0079_auto_20201103_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='checkordd',
            field=models.FloatField(default=0.0),
        ),
    ]
