# Generated by Django 3.1.2 on 2020-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0080_deposit_checkordd'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='rtgs',
            field=models.FloatField(default=0.0),
        ),
    ]
