# Generated by Django 3.1.2 on 2020-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0081_deposit_rtgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='Route_attached',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
