# Generated by Django 3.1.2 on 2020-11-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0082_village_route_attached'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='code',
            new_name='name',
        ),
    ]
