# Generated by Django 3.1.2 on 2020-11-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0083_auto_20201105_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloan',
            name='closingdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloan',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
