# Generated by Django 3.1.2 on 2020-11-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0084_auto_20201105_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='fullname',
            new_name='fname',
        ),
    ]
