# Generated by Django 3.1.2 on 2020-11-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0085_auto_20201106_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='fname',
            new_name='fullname',
        ),
    ]
