# Generated by Django 3.1.3 on 2020-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0087_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='mobileno',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
