# Generated by Django 3.1.3 on 2020-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0088_signup_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='checkordd',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='loan_no',
        ),
        migrations.AddField(
            model_name='deposit',
            name='checkorddno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='depositno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='rtgs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
