# Generated by Django 3.1.3 on 2020-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0089_auto_20201109_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contno',
            field=models.BigIntegerField(blank=True, default=1, max_length=15, null=True),
        ),
    ]
