# Generated by Django 3.1.2 on 2020-11-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0090_auto_20201109_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='checkorddno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='depositno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='rtgs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='issueddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
