# Generated by Django 3.1.2 on 2020-11-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0092_auto_20201110_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='contno',
            field=models.BigIntegerField(blank=True, default=1, null=True),
        ),
    ]
