# Generated by Django 3.1.2 on 2020-11-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0093_auto_20201110_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='center',
            new_name='centercode',
        ),
    ]
