# Generated by Django 3.1.3 on 2020-11-11 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0094_auto_20201110_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloan',
            old_name='center',
            new_name='centercode',
        ),
        migrations.RenameField(
            model_name='cloan',
            old_name='route',
            new_name='routecode',
        ),
    ]
