# Generated by Django 3.1.2 on 2020-11-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0095_auto_20201111_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='center',
            new_name='centercode',
        ),
        migrations.AddField(
            model_name='deposit',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='rtgs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='rtgs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
