# Generated by Django 3.1.2 on 2020-11-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0096_auto_20201116_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloan',
            old_name='centercode',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='cloan',
            old_name='routecode',
            new_name='route',
        ),
    ]
