# Generated by Django 3.1.3 on 2020-11-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0097_auto_20201116_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='Route_attached1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='Route_attached2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='Route_attached',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
