# Generated by Django 3.1.3 on 2020-11-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0098_auto_20201117_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily_data',
        ),
    ]
