# Generated by Django 3.1.3 on 2020-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0099_delete_daily_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleno', models.IntegerField(default=0)),
                ('sampleno2', models.IntegerField(default=0)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.FloatField(default=0.0)),
                ('ltrs', models.FloatField(default=0.0)),
                ('can', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('dateto', models.DateField(blank=True, null=True)),
                ('shift_from', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_to', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('tsrate', models.FloatField(blank=True, null=True)),
                ('comm', models.FloatField(blank=True, null=True)),
                ('pel', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ltrrate', models.FloatField(default=0.0)),
            ],
        ),
    ]
