# Generated by Django 3.1.3 on 2020-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0101_daily_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='High_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sampno', models.IntegerField(default=0)),
                ('sampno2', models.IntegerField(default=0)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('can', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='daily_report',
            name='shift_loc',
        ),
    ]
