# Generated by Django 3.1.3 on 2020-11-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0103_auto_20201123_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='high_report',
            old_name='date',
            new_name='dates',
        ),
        migrations.AddField(
            model_name='high_report',
            name='shift_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
