# Generated by Django 3.1.3 on 2020-11-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0105_auto_20201123_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='high_report',
            old_name='shift_loc1',
            new_name='shift',
        ),
    ]
