# Generated by Django 3.1.3 on 2020-11-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0106_auto_20201123_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='high_report',
            old_name='dates',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='high_report',
            old_name='shift',
            new_name='shift_loc',
        ),
        migrations.RemoveField(
            model_name='dok_entry',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='dok_entry',
            name='bank_no',
        ),
        migrations.RemoveField(
            model_name='dok_entry',
            name='mobile',
        ),
    ]
