# Generated by Django 3.1.3 on 2020-11-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0107_auto_20201123_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='high_report',
            name='routecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
