# Generated by Django 3.1.3 on 2020-11-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0108_high_report_routecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_data',
            old_name='ltrrate',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='sampleno',
            new_name='sampno',
        ),
        migrations.RenameField(
            model_name='daily_data',
            old_name='sampleno2',
            new_name='sampno2',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='bank_no',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='comm',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='datefrom',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='dateto',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='ltrs',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='pel',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='shift_from',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='shift_to',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='tsrate',
        ),
    ]
