# Generated by Django 3.1.3 on 2020-11-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0109_auto_20201123_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_data',
            old_name='shift_loc',
            new_name='shift',
        ),
        migrations.AddField(
            model_name='daily_data',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='comm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='ltrrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='ltrs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='pel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='tsrate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
