# Generated by Django 3.1.3 on 2020-11-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0112_auto_20201123_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_data',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
