# Generated by Django 3.1.3 on 2020-11-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0113_auto_20201123_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daily_report',
        ),
        migrations.DeleteModel(
            name='High_report',
        ),
    ]
