# Generated by Django 3.1.3 on 2020-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0114_auto_20201123_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='net',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
