# Generated by Django 3.1.3 on 2020-11-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0115_daily_data_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_data',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='comm',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='net',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='pel',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='tsrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
