# Generated by Django 3.1.3 on 2020-11-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0116_auto_20201125_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_data',
            name='net',
            field=models.FloatField(default=0.0),
        ),
    ]
