# Generated by Django 3.1.3 on 2020-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0117_auto_20201125_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_data',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='comm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='pel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='daily_data',
            name='tsrate',
            field=models.FloatField(default=0.0),
        ),
    ]
