# Generated by Django 3.1.3 on 2020-11-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0120_auto_20201125_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='agentcode',
            new_name='agent_name',
        ),
    ]
