# Generated by Django 3.1.3 on 2020-11-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0121_auto_20201125_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='BankBranch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='ifsccode',
            new_name='ifsc',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='routecode',
            new_name='route_number',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='supervisorcode',
            new_name='supervisor',
        ),
        migrations.RenameField(
            model_name='center',
            old_name='villagecode',
            new_name='village_name',
        ),
    ]
