# Generated by Django 3.1.3 on 2020-11-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0122_auto_20201126_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('graceperiod', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileno', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.signup')),
            ],
        ),
    ]
