# Generated by Django 3.1.3 on 2020-11-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0124_auto_20201126_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersdata',
        ),
    ]
