# Generated by Django 3.1.3 on 2020-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0128_auto_20201127_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastersname', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
