# Generated by Django 3.1.3 on 2020-12-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0130_remove_extendeduser_graceperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoK_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.IntegerField(default=0)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.FloatField(default=0.0)),
                ('cans', models.IntegerField(default=0)),
                ('routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QC_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('samplecode', models.IntegerField(default=0)),
                ('fat', models.FloatField(default=0.0)),
                ('clr', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
            ],
        ),
    ]
