# Generated by Django 3.1.3 on 2020-12-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0131_dok_bank_qc_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
