# Generated by Django 3.1.3 on 2020-12-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0134_auto_20201210_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='qc_bank',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qc_entry',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
