# Generated by Django 3.1.3 on 2020-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0135_auto_20201210_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
