# Generated by Django 3.1.3 on 2020-12-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0136_daily_data_remove'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='remove1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
