# Generated by Django 3.1.3 on 2020-12-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0137_daily_data_remove1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufalloMilkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('rate_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('snf_value', models.CharField(blank=True, max_length=255, null=True)),
                ('fixed_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('snf_deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('fat_from', models.FloatField(blank=True, default=0.0, null=True)),
                ('fat_to', models.FloatField(blank=True, default=0.0, null=True)),
                ('penalty_in_RS', models.FloatField(blank=True, default=0.0, null=True)),
                ('deduction_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('premium', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('commission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour_milk', models.CharField(blank=True, max_length=255, null=True)),
                ('curd', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('sour_milkrate', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BufalloMilkCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('rate_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('snf_value', models.CharField(blank=True, max_length=255, null=True)),
                ('fixed_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('snf_deduction', models.CharField(blank=True, max_length=255, null=True)),
                ('fat_from', models.FloatField(blank=True, default=0.0, null=True)),
                ('fat_to', models.FloatField(blank=True, default=0.0, null=True)),
                ('penalty_in_RS', models.FloatField(blank=True, default=0.0, null=True)),
                ('deduction_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('premium', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('commission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour_milk', models.CharField(blank=True, max_length=255, null=True)),
                ('curd', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('sour_milkrate', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BufalloMilkRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('rate_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('snf_value', models.CharField(blank=True, max_length=255, null=True)),
                ('fixed_value', models.FloatField(blank=True, default=0.0, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('snf_deduction', models.FloatField(blank=True, default=0.0, null=True)),
                ('fat_from', models.FloatField(blank=True, default=0.0, null=True)),
                ('fat_to', models.FloatField(blank=True, default=0.0, null=True)),
                ('penalty_in_RS', models.FloatField(blank=True, default=0.0, null=True)),
                ('deduction_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('premium', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('commission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sour_milk', models.CharField(blank=True, max_length=255, null=True)),
                ('curd', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('sour_milkrate', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinMaxBuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_SNF', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_SNF', models.FloatField(blank=True, default=0.0, null=True)),
                ('tsrate', models.FloatField(blank=True, default=0.0, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('commission', models.FloatField(blank=True, default=0.0, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bufallomilkcategory')),
                ('centercode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bufallomilkcenter')),
                ('routecode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.bufallomilkroute')),
            ],
        ),
    ]
