# Generated by Django 3.1.3 on 2020-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0139_dok_create_qc_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(blank=True, max_length=255, null=True)),
                ('dname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocode', models.CharField(blank=True, max_length=255, null=True)),
                ('oname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcode', models.CharField(blank=True, max_length=255, null=True)),
                ('rname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
