# Generated by Django 3.1.3 on 2020-12-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0140_department_office_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufallomilkcenter',
            name='routecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
