# Generated by Django 3.1.2 on 2020-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0142_daywisesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refcode', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Masters',
            new_name='Referral',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='mastersname',
            new_name='referralcode',
        ),
    ]
