# Generated by Django 3.1.4 on 2020-12-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0144_formulae_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulae',
            name='code',
        ),
    ]
