# Generated by Django 3.1.4 on 2020-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0145_remove_formulae_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='Email',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
