# Generated by Django 3.1.3 on 2020-12-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0146_center_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_data',
            name='remove',
        ),
        migrations.RemoveField(
            model_name='daily_data',
            name='remove1',
        ),
    ]
