# Generated by Django 3.1.3 on 2020-12-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0147_auto_20201217_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Daywisesreport',
        ),
    ]
