# Generated by Django 3.1.3 on 2020-12-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0148_delete_daywisesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPT_Daywisesreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('can', models.FloatField(default=0.0)),
                ('scan', models.FloatField(default=0.0)),
                ('qty', models.FloatField(default=0.0)),
                ('ltrs', models.FloatField(default=0.0)),
                ('fat', models.FloatField(default=0.0)),
                ('snf', models.FloatField(default=0.0)),
                ('sqty', models.FloatField(default=0.0)),
                ('sltrs', models.FloatField(default=0.0)),
                ('afat', models.FloatField(default=0.0)),
                ('asnf', models.FloatField(default=0.0)),
                ('kfat', models.FloatField(default=0.0)),
                ('ksnf', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('gamount', models.FloatField(default=0.0)),
            ],
        ),
    ]
