# Generated by Django 3.1.3 on 2020-12-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0149_rpt_daywisesreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RPT_Daywisesreport',
            new_name='Daywisesreport',
        ),
    ]
