# Generated by Django 3.1.3 on 2020-12-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0150_auto_20201222_2155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daywisesreport',
            new_name='RPT_Daywisesreport',
        ),
    ]
