# Generated by Django 3.1.4 on 2020-12-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0151_auto_20201222_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Route_attached1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='Route_attached2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
