# Generated by Django 3.1.2 on 2020-12-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0152_auto_20201228_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpt_bankwise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.IntegerField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('centre_code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bankno', models.CharField(blank=True, max_length=255, null=True)),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
