# Generated by Django 3.1.2 on 2020-12-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0153_rpt_bankwise'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_bankwise',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
