# Generated by Django 3.1.2 on 2020-12-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0154_rpt_bankwise_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_bankwise',
            name='centre_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rpt_bankwise',
            name='route_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
