# Generated by Django 3.1.4 on 2020-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0155_auto_20201230_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='centerdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CCode', models.CharField(max_length=255)),
                ('CenterName', models.CharField(max_length=255)),
                ('AgentName', models.CharField(max_length=255)),
                ('RName', models.CharField(max_length=255)),
                ('BC', models.CharField(max_length=255)),
                ('ContactNo', models.BigIntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
