# Generated by Django 3.1.4 on 2020-12-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0156_centerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerdata',
            name='ContactNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
