# Generated by Django 3.1.4 on 2020-12-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0157_auto_20201231_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='milkdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Shift', models.CharField(max_length=255)),
                ('Milktype', models.CharField(max_length=255)),
                ('kgs', models.FloatField(default=0.0)),
                ('Ltrs', models.FloatField(default=0.0)),
                ('Fat', models.FloatField(default=0.0)),
                ('Snf', models.FloatField(default=0.0)),
                ('RateLTR', models.FloatField(default=0.0)),
                ('Netamount', models.FloatField(default=0.0)),
                ('PiExp', models.FloatField(default=0.0)),
                ('Total', models.FloatField(default=0.0)),
            ],
        ),
    ]
