# Generated by Django 3.1.2 on 2021-01-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0158_milkdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='centre_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='route_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
