# Generated by Django 3.1.2 on 2021-01-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0161_excelextraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloan',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cloan',
            name='installment_amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloan',
            name='loan_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
