# Generated by Django 3.1.2 on 2021-01-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0163_loanbill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loanbill',
            new_name='Loanbillsdata',
        ),
    ]
