# Generated by Django 3.1.2 on 2021-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0167_rpt_milkbillreport_iamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerbank',
            name='accholdername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='centerbank',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
