# Generated by Django 3.1.2 on 2021-01-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0168_auto_20210119_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkdata',
            name='accholdername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='bankno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='centercode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='milkdata',
            name='PiExp',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
