# Generated by Django 3.1.4 on 2021-01-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0171_auto_20210121_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelupload',
            old_name='bankno',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='excelupload',
            old_name='centercode',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='bankno',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='centercode',
            new_name='center',
        ),
    ]
