# Generated by Django 3.1.2 on 2021-01-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0173_rpt_consolidatedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(blank=True, max_length=255)),
                ('pername', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usersdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('gname', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('isactive', models.BooleanField(default=True)),
                ('lastlogin', models.CharField(blank=True, max_length=255, null=True)),
                ('datejoined', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
