# Generated by Django 3.1.2 on 2021-01-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0174_groupsdata_usersdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='datejoined',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
