# Generated by Django 3.1.2 on 2021-01-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0176_extendeduser_referralcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='referralcode',
        ),
    ]
