# Generated by Django 3.1.2 on 2021-01-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0177_remove_extendeduser_referralcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
