# Generated by Django 3.1.2 on 2021-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0178_extendeduser_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='rpt_bufallomilk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('Routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('rate_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('min_fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_SNF', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_SNF', models.FloatField(blank=True, default=0.0, null=True)),
                ('tsrate', models.FloatField(blank=True, default=0.0, null=True)),
                ('categoryid', models.IntegerField(blank=True, default=0, null=True)),
                ('routeid', models.IntegerField(blank=True, default=0, null=True)),
                ('centerid', models.IntegerField(blank=True, default=0, null=True)),
                ('brid', models.IntegerField(blank=True, default=0, null=True)),
                ('bcenterid', models.IntegerField(blank=True, default=0, null=True)),
                ('bcategoryid', models.IntegerField(blank=True, default=0, null=True)),
                ('bfrom_date', models.DateField(blank=True, null=True)),
                ('bto_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rpt_cowmilk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('Routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('rate_calculation', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_type', models.CharField(blank=True, max_length=255, null=True)),
                ('milk_type', models.CharField(blank=True, max_length=255, null=True)),
                ('min_fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('min_SNF', models.FloatField(blank=True, default=0.0, null=True)),
                ('max_SNF', models.FloatField(blank=True, default=0.0, null=True)),
                ('tsrate', models.FloatField(blank=True, default=0.0, null=True)),
                ('categoryid', models.IntegerField(blank=True, default=0, null=True)),
                ('routeid', models.IntegerField(blank=True, default=0, null=True)),
                ('centerid', models.IntegerField(blank=True, default=0, null=True)),
                ('crid', models.IntegerField(blank=True, default=0, null=True)),
                ('ccenterid', models.IntegerField(blank=True, default=0, null=True)),
                ('ccategoryid', models.IntegerField(blank=True, default=0, null=True)),
                ('cfrom_date', models.DateField(blank=True, null=True)),
                ('cto_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='minmaxbuff',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='minmaxfat',
            name='commission',
        ),
    ]
