# Generated by Django 3.1.2 on 2021-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0180_auto_20210123_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
