# Generated by Django 3.1.2 on 2021-01-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0181_auto_20210123_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
