# Generated by Django 3.1.2 on 2021-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0182_auto_20210123_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='pin',
            field=models.IntegerField(unique=True),
        ),
    ]
