# Generated by Django 3.1.3 on 2021-01-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0186_auto_20210123_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='bankname1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='branch1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='ifsc1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
