# Generated by Django 3.1.4 on 2021-01-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0187_auto_20210125_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='BM_Cartage_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='BM_comm_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='CM_Cartage_amount',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
