# Generated by Django 3.1.4 on 2021-01-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0188_auto_20210125_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='CM_comm_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
