# Generated by Django 3.1.2 on 2021-01-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0193_auto_20210125_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_bankwise',
            name='idate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpt_bankwise',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
