# Generated by Django 3.1.2 on 2021-01-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0194_auto_20210126_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_bankwise',
            name='idate',
        ),
    ]
