# Generated by Django 3.1.2 on 2021-01-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0195_remove_rpt_bankwise_idate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_bankwise',
            name='ddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpt_bankwise',
            name='net',
            field=models.FloatField(default=0.0),
        ),
    ]
