# Generated by Django 3.1.3 on 2021-01-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0200_rpt_milkbillvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='bankname1',
        ),
        migrations.RemoveField(
            model_name='center',
            name='branch1',
        ),
        migrations.RemoveField(
            model_name='center',
            name='ifsc1',
        ),
    ]
