# Generated by Django 3.1.3 on 2021-01-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0201_auto_20210128_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='bankname1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='branch1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='ifsc1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
