# Generated by Django 3.1.2 on 2021-01-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0202_auto_20210128_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contno',
            field=models.BigIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='pin',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
