# Generated by Django 3.1.2 on 2021-01-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0203_auto_20210129_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dcode',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
