# Generated by Django 3.1.2 on 2021-01-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0205_auto_20210129_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='ocode',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='oname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
