# Generated by Django 3.1.2 on 2021-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0206_auto_20210129_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulae',
            name='desc',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='formulae',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
