# Generated by Django 3.1.2 on 2021-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0208_auto_20210129_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milktype',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='milktype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
