# Generated by Django 3.1.2 on 2021-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0210_auto_20210130_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='installment_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='interest_amt',
            field=models.FloatField(default=0.0),
        ),
    ]
