# Generated by Django 3.1.2 on 2021-02-01 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0211_auto_20210131_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_daywisesreport',
            name='can',
        ),
        migrations.RemoveField(
            model_name='rpt_daywisesreport',
            name='scan',
        ),
    ]
