# Generated by Django 3.1.2 on 2021-02-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0213_auto_20210202_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_milkbillreport',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
