# Generated by Django 3.1.2 on 2021-02-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0216_auto_20210202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dok_bank',
            name='samplecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dok_create',
            name='samplecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='centercode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='centre_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='routecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
