# Generated by Django 3.1.4 on 2021-02-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0217_auto_20210203_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPT_Milkbilldate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('dateto', models.DateField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
