# Generated by Django 3.1.2 on 2021-02-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0218_rpt_milkbilldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='description',
        ),
    ]
