# Generated by Django 3.1.2 on 2021-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0221_extendeduser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Route_attached', models.CharField(blank=True, max_length=255, null=True)),
                ('Route_attached1', models.CharField(blank=True, max_length=255, null=True)),
                ('Route_attached2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
