# Generated by Django 3.1.2 on 2021-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0222_agent1'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
