# Generated by Django 3.1.2 on 2021-02-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0223_agent_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloan',
            name='installment_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cloan',
            name='interest_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='installment_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='interest_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
