# Generated by Django 3.1.2 on 2021-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0225_auto_20210216_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Route_attached', models.CharField(blank=True, max_length=255, null=True)),
                ('Route_attached1', models.CharField(blank=True, max_length=255, null=True)),
                ('Route_attached2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
