# Generated by Django 3.1.2 on 2021-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0226_auto_20210216_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_milkbillvoucher',
            name='comm',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
