# Generated by Django 3.1.2 on 2021-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0227_rpt_milkbillvoucher_comm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cartage', models.CharField(blank=True, max_length=255, null=True)),
                ('cattlefeed', models.CharField(blank=True, max_length=255, null=True)),
                ('centercode', models.CharField(blank=True, max_length=255, null=True)),
                ('autofine', models.CharField(blank=True, max_length=255, null=True)),
                ('stores', models.CharField(blank=True, max_length=255, null=True)),
                ('aarrears', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine', models.CharField(blank=True, max_length=255, null=True)),
                ('aothers', models.CharField(blank=True, max_length=255, null=True)),
                ('stationary', models.CharField(blank=True, max_length=255, null=True)),
                ('commission', models.CharField(blank=True, max_length=255, null=True)),
                ('emtcharges', models.CharField(blank=True, max_length=255, null=True)),
                ('seed', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance', models.CharField(blank=True, max_length=255, null=True)),
                ('rarrears', models.CharField(blank=True, max_length=255, null=True)),
                ('rothers', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
