# Generated by Django 3.1.2 on 2021-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0228_additions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
