# Generated by Django 3.1.2 on 2021-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0231_auto_20210219_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_number', models.CharField(max_length=255, unique=True)),
                ('Route_name', models.CharField(max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
