# Generated by Django 3.1.2 on 2021-02-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0232_auto_20210219_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcode', models.CharField(max_length=255, unique=True)),
                ('dname', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
