# Generated by Django 3.1.2 on 2021-02-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0234_auto_20210219_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='rname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
