# Generated by Django 3.1.2 on 2021-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0235_auto_20210219_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rcode',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
