# Generated by Django 3.1.2 on 2021-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0236_auto_20210219_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocode', models.CharField(max_length=255, unique=True)),
                ('oname', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
