# Generated by Django 3.1.2 on 2021-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0240_auto_20210219_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='remove',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
