# Generated by Django 3.1.2 on 2021-02-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0242_auto_20210220_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='mobileno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
