# Generated by Django 3.0.4 on 2021-02-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0243_auto_20210222_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloan',
            name='installment_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='cloan',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='installment_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
