# Generated by Django 3.0.4 on 2021-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0244_auto_20210223_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloan',
            name='interest_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='interest_amt',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
