# Generated by Django 3.1.4 on 2021-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0245_auto_20210223_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='aarrears',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='acentercode',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='aothers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='autofine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='cartage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='cattlefeed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='emtcharges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='installment_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='insurance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='interest_amt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='medicine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='rarrears',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='rothers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='seed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='stationary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='rpt_milkbillvoucher',
            name='stores',
            field=models.FloatField(default=0.0),
        ),
    ]
