# Generated by Django 3.1.4 on 2021-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0246_auto_20210224_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='centername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='daily_data',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
