# Generated by Django 3.1.2 on 2021-03-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0248_rpt_daywiseabstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_daywiseabstract',
            name='Shift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
