# Generated by Django 3.1.2 on 2021-03-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0249_rpt_daywiseabstract_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_daywiseabstract',
            name='routecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
