# Generated by Django 3.1.2 on 2021-03-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0251_rpt_daywiseabstract_pel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_daywiseabstract',
            name='pel',
        ),
    ]
