# Generated by Django 3.1.2 on 2021-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0252_remove_rpt_daywiseabstract_pel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPT_Routewisebillabstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routecode', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.FloatField(blank=True, default=0.0, null=True)),
                ('Ltrs', models.FloatField(blank=True, default=0.0, null=True)),
                ('fatkgs', models.FloatField(blank=True, default=0.0, null=True)),
                ('afat', models.FloatField(default=0.0)),
                ('snfkgs', models.FloatField(blank=True, default=0.0, null=True)),
                ('asnf', models.FloatField(default=0.0)),
                ('amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Snf1', models.FloatField(blank=True, default=0.0, null=True)),
                ('comm', models.FloatField(blank=True, default=0.0, null=True)),
                ('exsamt', models.FloatField(blank=True, default=0.0, null=True)),
                ('cartage', models.FloatField(default=0.0)),
                ('aothers', models.FloatField(default=0.0)),
                ('gamount', models.FloatField(blank=True, default=0.0, null=True)),
                ('loan_no', models.CharField(blank=True, max_length=255, null=True)),
                ('stores', models.FloatField(default=0.0)),
                ('rothers', models.FloatField(default=0.0)),
                ('net', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
