# Generated by Django 3.1.2 on 2021-03-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0253_rpt_routewisebillabstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_daywiseabstract',
            old_name='Snf1',
            new_name='ltrrate',
        ),
        migrations.AddField(
            model_name='rpt_daywiseabstract',
            name='pel',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='rpt_daywiseabstract',
            name='tsrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
