# Generated by Django 3.1.2 on 2021-03-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0254_auto_20210302_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_daywiseabstract',
            name='cartage',
        ),
        migrations.RemoveField(
            model_name='rpt_daywiseabstract',
            name='incentive',
        ),
    ]
