# Generated by Django 3.1.2 on 2021-03-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0255_auto_20210302_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_daywiseabstract',
            old_name='tsrate',
            new_name='amount',
        ),
    ]
