# Generated by Django 3.1.2 on 2021-03-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0256_auto_20210302_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpt_daywiseabstract',
            old_name='pel',
            new_name='tsrate',
        ),
    ]
