# Generated by Django 3.1.2 on 2021-03-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0257_auto_20210302_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_routewisebillabstract',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
