# Generated by Django 3.1.2 on 2021-03-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0258_rpt_routewisebillabstract_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_routewisebillabstract',
            name='centercode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
