# Generated by Django 3.1.2 on 2021-03-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0259_rpt_routewisebillabstract_centercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additions',
            name='centercode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
