# Generated by Django 3.1.2 on 2021-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0261_rpt_routewisebillabstract_aarrears'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_routewisebillabstract',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
