# Generated by Django 3.1.2 on 2021-03-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0265_auto_20210312_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mobileno',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
