# Generated by Django 3.1.4 on 2021-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0266_auto_20210315_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='routename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
