# Generated by Django 3.1.4 on 2021-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0267_auto_20210317_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='centername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
