# Generated by Django 3.1.3 on 2021-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0268_daily_data_centername'),
    ]

    operations = [
        migrations.AddField(
            model_name='minmaxbuff',
            name='category1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minmaxbuff',
            name='centercode1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minmaxbuff',
            name='routecode1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minmaxfat',
            name='centercode1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='minmaxfat',
            name='routecode1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bufallomilkroute',
            name='snf_deduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cowmilkroute',
            name='snf_deduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
