# Generated by Django 3.1.4 on 2021-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0269_auto_20210324_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('Shift', models.CharField(max_length=255)),
                ('centercode', models.CharField(max_length=255)),
                ('Milktype', models.CharField(max_length=255)),
                ('kgs', models.FloatField(blank=True, default=0.0, null=True)),
                ('Ltrs', models.FloatField(blank=True, default=0.0, null=True)),
                ('afat', models.FloatField(blank=True, default=0.0, null=True)),
                ('asnf', models.FloatField(blank=True, default=0.0, null=True)),
                ('Fat', models.FloatField(blank=True, default=0.0, null=True)),
                ('Snf', models.FloatField(blank=True, default=0.0, null=True)),
                ('RateLTR', models.FloatField(blank=True, default=0.0, null=True)),
                ('pel', models.FloatField(blank=True, default=0.0, null=True)),
                ('gamount', models.FloatField(blank=True, default=0.0, null=True)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
    ]
