# Generated by Django 3.1.4 on 2021-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0270_dashboard_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='actholdername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
