# Generated by Django 3.1.4 on 2021-04-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0273_rpt_centerwisesreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RPT_Centerwisesreport',
        ),
    ]
