# Generated by Django 3.1.4 on 2021-04-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0274_delete_rpt_centerwisesreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_bankwise',
            name='net',
        ),
        migrations.RemoveField(
            model_name='rpt_bankwise',
            name='total',
        ),
    ]
