# Generated by Django 3.1.4 on 2021-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0275_auto_20210416_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_bankwise',
            name='net',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rpt_bankwise',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
