# Generated by Django 3.1.4 on 2021-04-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0276_auto_20210416_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpt_excel_bankwise',
            name='net',
        ),
        migrations.RemoveField(
            model_name='rpt_excel_bankwise',
            name='total',
        ),
    ]
