# Generated by Django 3.1.4 on 2021-04-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0279_auto_20210427_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_data',
            name='ltrtsrate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
