# Generated by Django 3.1.4 on 2021-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0280_daily_data_ltrtsrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpt_consolidated',
            name='branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
