from django.conf.urls import url, include
from . import views
from django.conf import settings

app_name = 'school'

urlpatterns = [
    # url(r'^fileupload/$',views.model_form_upload, name='model_form_upload'),
    # url(r'^pdf-download/$',views.pdf_download, name='pdf_download'),
    url(r'^logreportexcel/(?P<slug>.*)/$', views.logreportexcel, name='logreportexcel'),
    url(r'^emailsending/$', views.email, name='email'),
    url(r'^logreport/$', views.logfile, name='logfile'),
    url(r'^daily-edit/(?P<id>[0-9]+)/$', views.edit_update, name='edit_update'),
    url(r'^center_wise/$', views.center_wise, name='center_wise'),
    url(r'^center_wise/$', views.center_wise, name='center_wise'),
    url(r'^cloan/$', views.cloan, name='cloan'),
    url(r'^loanbilldate/$', views.loanbilldate, name='loanbilldate'),
    url(r'^deposit/$', views.deposit, name='deposit'),
    url(r'^depositreport/$', views.depositreport, name='depositreport'),
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^refundreport/$', views.refundreport, name='refundreport'),
    url(r'^excel_milkcollection/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_milkcollection, name='excel_milkcollection'),
    url(r'^signup/(?P<slug>.*)/$', views.signup, name='signup'),    
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^apassword/$', views.changepassword, name='changepassword'),
    url(r'^otp/$', views.otp, name='otp'),
    url(r'^milkbill/$', views.milkbill, name='milkbill'),
    url(r'^milkbill1/$', views.milkbill1, name='milkbill1'),
    url(r'^milkbillchange/(?P<slug3>.*)/$', views.milkbillchange, name='milkbill'),
    url(r'^bank_wise/$', views.bank_wise, name='bank_wise'),
    url(r'^daily_data/$', views.daily_data, name='daily_data'),
    url(r'^bank_report/$', views.bank_report, name='bank_report'),
    url(r'^branchreport/$', views.branchreport, name='branchreport'),
    url(r'^routereport/$', views.routereport, name='routereport'),
    url(r'^supervisorreport/$', views.supervisorreport, name='supervisorreport'),
    url(r'^agentreport/$', views.agentreport, name='agentreport'),
    url(r'^departmentreport/$', views.departmentreport, name='departmentreport'),
    url(r'^rolereport/$', views.rolereport, name='rolereport'),
    url(r'^officereport/$', views.officereport, name='officereport'),
    url(r'^villagereport/$', views.villagereport, name='villagereport'),
    url(r'^milktypereport/$', views.milktypereport, name='milktypereport'),
    url(r'^categoryreport/$', views.categoryreport, name='categoryreport'),
    url(r'^formulaereport/$', views.formulaereport, name='formulaereport'),
    url(r'^centerreport/$', views.centerreport, name='centerreport'),
    url(r'^centerreportdetails/(?P<slug>.*)/$', views.centerreportdetails, name='centerreportdetails'),
    url(r'^centerreportbank/$', views.centerreportbank, name='centerreportbank'),
    url(r'^loanreport/$', views.loanreport, name='loanreport'),
    url(r'^groupdata/$', views.groupsdata, name='groupsdata'),
    url(r'^groupdata1/$', views.groupsdata1, name='groupsdata1'),
    url(r'^loanbillreport/$', views.loanbillreport, name='loanbillreport'),
    url(r'^loanbillsreport/$', views.loanbillsreport, name='loanbillsreport'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^referral/$', views.referral, name='referral'),
    url(r'^bufallo-milk-center/$', views.bufallo_milk_center, name='bufallo_milk_center'),
    url(r'^bufallo-milk-route/$', views.bufallo_milk_route, name='bufallo_milk_route'),
    url(r'^bufallo-milk-category/$', views.bufallo_milk_category, name='bufallo_milk_category'),
    url(r'^passwordchange/$', views.change_password_done, name='change_password_done'),
    url(r'^day_wise/$', views.daywise, name='day_wise'),
    url(r'^daily-trans/$', views.daily_trans, name='daily_trans'),
    url(r'^update-data/$', views.update_data, name='update_data'),
    url(r'^updateho/$', views.update_dataho, name='update_dataho'),
    url(r'^updatemodelho/$', views.csv_update_ratesho, name='csv_update_ratesho'),
    url(r'^match-data/$', views.match_data, name='match_data'),
    url(r'^data/$', views.csv_data_model, name='csv_data_model'),
   # url(r'^dataupdate/$', views.csv_updatedata_model, name='csv_updatedata_model'),
    url(r'^updatemodel/$', views.csv_update_rates, name='csv_update_rates'),
    url(r'^qcentry-form/$', views.qc_form, name='qc_form'),
    url(r'^dockentry-form/$', views.dockentry_form, name='dockentry-form'),
    url(r'^manage_dok/$', views.manage_dok, name='manage_dok'),
    url(r'^csv_dok_entry/$', views.csv_dok_entry, name='csv_dok_entry'),
    url(r'^manage_qc/$', views.manage_qc, name='manage_qc'),
    url(r'^csv_qc_entry/$', views.csv_qc_entry, name='csv_qc_entry'),
    url(r'^cow-milk-route/$', views.cow_milk_route, name='cow_milk_route'),
    url(r'^cow-milk-center/$', views.cow_milk_center, name='cow_milk_center'),
    url(r'^cow-milk-category/$', views.cow_milk_category, name='cow_milk_category'),
    url(r'^managecowcategory/$', views.managecowcategory, name='managecowcategory'),
    url(r'^managecowcategory1/$', views.managecowcategory1, name='managecowcategory1'),
    url(r'^managecowroute/$', views.managecowroute, name='managecowroute'),
    url(r'^managecowroute1/$', views.managecowroute1, name='managecowroute1'),
    url(r'^managecowcenter/$', views.managecowcenter, name='managecowcenter'),
    url(r'^managecowcenter1/$', views.managecowcenter1, name='managecowcenter1'),
    url(r'^managebuffcategory/$', views.managebuffcategory, name='managebuffcategory'),
    url(r'^managebuffcategory1/$', views.managebuffcategory1, name='managebuffcategory1'),
    url(r'^managebuffroute/$', views.managebuffroute, name='managebuffroute'),
    url(r'^managebuffroute1/$', views.managebuffroute1, name='managebuffroute1'),
    url(r'^managebuffcenter/$', views.managebuffcenter, name='managebuffcenter'),
    url(r'^managebuffcenter1/$', views.managebuffcenter1, name='managebuffcenter1'),
    url(r'^cm-center-report/$', views.cm_center_report, name='cm-center-report'),
    url(r'^cm-category-report/$', views.cm_category_report, name='cm-category-report'),
    url(r'^cm-route-report/$', views.cm_route_report, name='cm-route-report'),
    url(r'^bm-center-report/$', views.bm_center_report, name='bm-center-report'),
    url(r'^bm-category-report/$', views.bm_category_report, name='bm-category-report'),
    url(r'^bm-route-report/$', views.bm_route_report, name='bm-route-report'),
    # url(r'^cowmilk-center-view/(?P<id>[0-9]+)/$',views.cowmilkviewcenter, name='cowmilkviewcenter'),
    url(r'^milk-form-view/(?P<id>[0-9]+)/$', views.milkform_view, name='milkform_view'),
    url(r'^condition-edit/(?P<id>[0-9]+)/$', views.conditionEdit, name='condition-edit'),
    url(r'^condition-update/(?P<id>[0-9]+)/$', views.conditionUpdate, name='condition-update'),
    url(r'^checked-delete/$', views.checked_delete, name='checked_delete'),
    url(r'^route/$', views.route, name='route'),
    url(r'^manageroute/$', views.manageroute, name='manageroute'),
    url(r'^manage_route/$', views.manage_route, name='manage_route'),

    url(r'^center_milk/$', views.center_milk, name='center_milk'),
    url(r'^manage_center/$', views.manage_center, name='manage_center'),
    url(r'^managecenter/$', views.managecenter, name='managecenter'),
    url(r'^center/$', views.center, name='center'),    url(r'^centerlist/$', views.centerlist, name='centerlist'),
    url(r'^excelupload/$', views.excelupload, name='excelupload'),
    url(r'^tsratesexcel/$', views.tsratesexcel1, name='tsratesexcel1'),
    url(r'^tsratescowroute/$', views.tsratescowroute, name='tsratescowroute'),
    url(r'^tsratescowcenter/$', views.tsratescowcenter, name='tsratescowcenter'),
    url(r'^tsratesbuffcategory/$',views.tsratesbuffcategory,name='tsratesbuffcategory'),
    url(r'^tsratesbuffroute/$', views.tsratesbuffroute, name='tsratesbuffroute'),
    url(r'^tsratesbuffcenter/$', views.tsratesbuffcenter, name='tsratesbuffcenter'),
    # url(r'^transaction-details/$',views.transaction_details, name='transaction_details'),
    url(r'^transaction/$', views.transaction_form, name='transaction_form'),
    url(r'^transaction/(?P<id>[0-9]+)/(?P<slug>.*)/$', views.transaction, name='transaction'),
    url(r'^rate/$', views.milk_rate, name='milk_rate'),
    url(r'^supervisor/$', views.supervisor, name='supervisor'),
    url(r'^additionsreport/$', views.additionsreport, name='additionsreport'),
    url(r'^exceladditionsreport/(?P<slug>.*)/$', views.excel_downloadadditionsreport, name='excel_downloadadditionsreport'),
    url(r'^manage_supervisor/$', views.manage_supervisor, name='manage_supervisor'),
    url(r'^managesupervisor/$', views.managesupervisor, name='managesupervisor'),
    url(r'^agent/$', views.agent, name='agent'),
    url(r'^manage/$', views.manage, name='manage'),
    #url(r'^manage_agent/$', views.manage_agent, name='manage_agent'),
    url(r'^manageagent/$', views.manageagent, name='manageagent'),
    url(r'^additions/$', views.additions, name='additions'),
    url(r'^additionsho/$', views.additionsho, name='additionsho'),
    url(r'^additionsho1/$', views.additionsho1, name='additionsho1'),
    url(r'^village/$', views.village, name='village'),
    url(r'^village1/$', views.village1, name='village1'),
    url(r'^manage_village/$', views.manage_village, name='manage_village'),
    url(r'^manage1/$', views.manage1, name='manage1'),
   # url(r'^village/$', views.village, name='village'),
    url(r'^milktype/$', views.milktype, name='milktype'),
    url(r'^managemilktype/$', views.managemilktype, name='managemilktype'),
    url(r'^manage_milktype/$', views.manage_milktype, name='manage_milktype'),

    url(r'^category/$', views.category, name='category'),
    url(r'^managecategory/$', views.managecategory, name='managecategory'),
    url(r'^manage_category/$', views.manage_category, name='manage_category'),

    url(r'^formulae/$', views.formulae, name='formulae'),
    url(r'^manageformulae/$', views.manageformulae, name='manageformulae'),
    url(r'^manage_formulae/$', views.manage_formulae, name='manage_formulae'),

    url(r'^bank/$', views.bank, name='bank'),
    url(r'^managebank/$', views.managebank, name='managebank'),
    url(r'^manage_bank/$', views.manage_bank, name='manage_bank'),

    url(r'^branch/$', views.branch, name='branch'),
    url(r'^managebranch/$', views.managebranch, name='managebranch'),
    #url(r'^manage_agent/$', views.manage_agent, name='manage_agent'),
    url(r'^manage_branch/$', views.manage_branch, name='manage_branch'),
    url(r'^userdata/$', views.users_data, name='userdata'),
    url(r'^users_data/$', views.users_data, name='userdata'),

    url(r'^consolidated/$', views.consolidated, name='consolidated'),
    url(r'^milkcollection/$', views.milkcollectionreport, name='milkcollectionreport'),
    url(r'^dashboardbranch/$', views.dashboardbranch, name='dashboardbranch'),
    #url(r'^dashboardbranchchange/(?P<slug>.*)/$', views.dashboardbranchchange, name='dashboardbranchchange'),
    url(r'^daywiseabstract/$', views.daywiseabstract, name='daywiseabstract'),
    url(r'^routewisebillabstract/$', views.routewisebillabstract, name='routewisebillabstract'),

    url(r'^down/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/$', views.pdf_month, name='pdf_month'),
    # url(r'^pdf1/$', views.GeneratePdf1, name='pdf_download'),
    url(r'^excel/(?P<slug>.*)/$', views.excel_download, name='excel_download'),
    url(r'^excel1/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_download1, name='excel_download'),
    url(r'^excel2/(?P<slug>.*)/$', views.excel_download2, name='excel_download'),
    url(r'^excel3/$', views.excel_download3, name='excel_download'),
    url(r'^centerwise/$', views.centerwise, name='centerwise'),
    url(r'^excel4/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_download4, name='excel_download'),
    url(r'^excel5/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_download5, name='excel_download'),
    url(r'^excel6/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug>.*)/(?P<slug1>.*)/$', views.excel_download6, name='excel_download'),
    url(r'^excelbank6/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug>.*)/(?P<slug1>.*)/$', views.excel_downloadbank6, name='excel_downloadbank6'),
    url(r'^excel-center-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/$', views.excel_downloadcenter, name='excel_downloadcenter'),
    url(r'^excel-center-reportbank/(?P<slug>.*)/(?P<slug1>.*)/$', views.excel_downloadcenterbank, name='excel_downloadcenterbank'),
    url(r'^excel-bmcenter-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_downloadbmcenter, name='excel_downloadbmcenter'),
    url(r'^excel-bmroute-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_downloadbmroute, name='excel_downloadbmroute'),
    url(r'^excel-bmcategory-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_downloadbmcategory, name='excel_downloadbmcategory'),
    url(r'^excel-cmcenter-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_downloadcmcenter, name='excel_downloadcmcenter'),
    url(r'^excel-cmroute-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_downloadcmroute, name='excel_downloadcmroute'),
    url(r'^excel-cmcategory-report/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_downloadcmcategory, name='excel_downloadcmcategory'),
    url(r'^excel-branch-report/(?P<slug>.*)/$', views.excel_downloadbranch, name='excel_downloadbranch'),
    url(r'^excel-route-report/(?P<slug>.*)/$', views.excel_downloadroute, name='excel_downloadroute'),
    url(r'^excel-supervisor-report/(?P<slug>.*)/$', views.excel_downloadsupervisor, name='excel_downloadsupervisor'),
    url(r'^excel-agent-report/(?P<slug>.*)/$', views.excel_downloadagent, name='excel_downloadagent'),
    url(r'^excel-department-report/(?P<slug>.*)/$', views.excel_downloaddepartment, name='excel_downloaddepartment'),
    url(r'^excel-role-report/(?P<slug>.*)/$', views.excel_downloadrole, name='excel_downloadrole'),
    url(r'^excel-office-report/(?P<slug>.*)/$', views.excel_downloadoffice, name='excel_downloadoffice'),
    url(r'^excel-village-report/(?P<slug>.*)/$', views.excel_downloadvillage, name='excel_downloadvillage'),
    url(r'^excel-category-report/(?P<slug>.*)/$', views.excel_downloadcategory, name='excel_downloadcategory'),
    url(r'^excel-milktype-report/(?P<slug>.*)/$', views.excel_downloadmilktype, name='excel_downloadmilktype'),
    url(r'^excel-formula-report/(?P<slug>.*)/$', views.excel_downloadformula, name='excel_downloadformula'),
    url(r'^excel-user-report/(?P<slug>.*)/(?P<slug1>.*)/$', views.excel_downloaduser, name='excel_downloaduser'),
    #url(r'^excel_consolidated/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_consolidated, name='excel_consolidated'),
    url(r'^excel_consolidated/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_consolidated, name='excel_consolidated'),
    url(r'^excel_loanreport/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_loanreport, name='excel_loanreport'),
    url(r'^excel_daywiseabstract/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/(?P<slug4>.*)/$', views.excel_daywiseabstract, name='excel_daywiseabstract'),
    url(r'^excel_routewisebillabstract/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_routewisebillabstract, name='excel_routewisebillabstract'),
    url(r'^excel_depositreport/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_depositreport, name='excel_depositreport'),
    url(r'^excel_refundreport/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/(?P<slug3>.*)/$', views.excel_refundreport, name='excel_refundreport'),
    url(r'^role/$', views.role, name='role'),
    url(r'^managerole/$', views.managerole, name='managerole'),
    url(r'^manage_role/$', views.manage_role, name='manage_role'),

    url(r'^department/$', views.department, name='department'),
    url(r'^managedepartment/$', views.managedepartment, name='managedepartment'),
    url(r'^manage_department/$', views.manage_department, name='manage_department'),


    url(r'^office/$', views.office, name='office'),
    url(r'^manageoffice/$', views.manageoffice, name='manageoffice'),
    url(r'^manage_office/$', views.manage_office, name='manage_office'),

    url(r'^excel-data/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/$', views.excel_download_date,
        name='excel_download_date'),
    url(r'^excel-data1/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/$', views.excel_download_date1,
        name='excel_download_date1'),
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^course/$', views.course, name='course'),
    url(r'^teacher/$', views.teacher, name='teacher'),
    url(r'^report/$', views.report, name='report'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^milkbilldata/$', views.milkbilldata, name='milkbilldata'),
    url(r'^centerextraction/$', views.centerexcelextraction, name='centerexcelextraction'),
    url(r'^milkbillextraction/$', views.milkbillextraction, name='milkbillextraction'),
    url(r'^centerbankdata/$', views.centerbankdata, name='centerbankdata'),
    url(r'^$', views.index, name='index'),
     
    # url(r'^register/$', views.register, name='register'),
    
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard-report/$', views.dashboard_report, name='dashboard_report'),
    url(r'^data-upload/$', views.data_upload, name='data_upload'),
    url(r'^csv-upload/$',views.csv_upload, name='csv_upload'),
    url(r'^check-report/$', views.check_report, name='data_upload'),
    url(r'^ledger/$', views.layer, name='layer'),
    # url(r'^pdf/(?P<slug>.*)$',views.pdf_month, name='pdf_month'),
    url(r'^layer-detail/(?P<slug>.*)/$', views.layerdetail, name='layerdetail'),
    url(r'^layer-detail-date/(?P<slug>.*)/(?P<slug1>.*)/(?P<slug2>.*)/$', views.layerdetail_date,
        name='layerdetail_date'),

]


